@Articles.Api_HostAddress = http://localhost:5062

GET {{Articles.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Articles.Api_HostAddress}}/v1/articles/
Content-Type: application/json
Accept: application/json

{
    "title": "sadasp",
    "description": "sd",
    "body":"akdpksap"
}

###
